general.import = ["~/.config/alacritty/theme.toml"]

[window]
padding = { x = 21, y = 12 }
opacity = 0.81
option_as_alt = "Both"

[font]
normal = { family = "GeistMono Nerd Font", style = "Medium" }
bold = { family = "GeistMono Nerd Font", style = "Medium" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Off" }

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
