general.import = ["~/.config/alacritty/theme.toml"]

[window]
padding = { x = 21, y = 12 }
decorations = "buttonless"
opacity = 0.77
blur = true
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[font]
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
# normal = { family = "MesloLGM Nerd Font", style = "Regular" }
# bold = { family = "MesloLGM Nerd Font", style = "Bold" }
normal = { family = "GeistMono Nerd Font", style = "Medium" }
bold = { family = "GeistMono Nerd Font", style = "Medium" }
size = 16
# offset = { y = 3 }
# glyph_offset = { y = 6 }
# builtin_box_drawing = false

[cursor]
style = { shape = "Block", blinking = "Off" }
# style = { shape = "Underline", blinking = "Always" }
# style = { shape = "Beam", blinking = "Always" }

[env]
# TERM = "tmux-256color"
TERM = "xterm-256color"
COLORTERM = "truecolor"
